// Generates `pubspec_overrides.yaml` from the contents of the
// top-level `integrations/` directory.
//
// For each validated integration discovered under
// `integrations/<name>/pubspec.yaml`, an entry
//
//   <name>:
//     path: integrations/<name>
//
// is added under `dependency_overrides:`. When the directory contains
// no integrations, the existing `pubspec_overrides.yaml` (if any) is
// removed so that `flutter pub get` resolves the host's regular
// dependencies cleanly.
//
// Discovery and validation live in `_extension_discovery.dart`; this
// script only formats the output.
//
// Usage:
//   dart run scripts/gen_extension_overrides.dart
//
// Run via the `make ext-gen` target (which also regenerates
// `lib/extension/generated/registry.g.dart`).

import 'dart:io';

import '_extension_discovery.dart';

const String _outputFile = 'pubspec_overrides.yaml';
const String _generatedHeader =
    '# AUTO-GENERATED by `make ext-gen`. Do not edit by hand.\n'
    '# Regenerated from the contents of the `integrations/` directory.\n'
    '# When no integrations are present this file is removed entirely.\n';

Future<void> main(List<String> args) async {
  final IntegrationDiscoveryResult result = discoverIntegrations();
  for (final String warning in result.warnings) {
    stderr.writeln('[gen_extension_overrides] $warning');
  }

  if (result.integrations.isEmpty) {
    _removeIfPresent(_outputFile);
    stdout.writeln(
      '[gen_extension_overrides] no integrations discovered; '
      'removed any existing $_outputFile.',
    );
    return;
  }

  final StringBuffer buf = StringBuffer()
    ..write(_generatedHeader)
    ..writeln('dependency_overrides:');
  for (final DiscoveredIntegration integration in result.integrations) {
    buf
      ..writeln('  ${integration.name}:')
      ..writeln('    path: ${integration.path}');
  }

  File(_outputFile).writeAsStringSync(buf.toString());
  stdout.writeln(
    '[gen_extension_overrides] wrote $_outputFile with '
    '${result.integrations.length} integration(s): '
    '${result.integrations.map((DiscoveredIntegration i) => i.name).join(', ')}.',
  );
}

void _removeIfPresent(String path) {
  final File file = File(path);
  if (file.existsSync()) {
    file.deleteSync();
  }
}
