// Generates `lib/extension/generated/registry.g.dart` from the
// contents of the top-level `integrations/` directory.
//
// For each validated integration discovered under
// `integrations/<name>/pubspec.yaml`, an `import` of
// `package:<name>/<name>.dart` is emitted, along with an entry in the
// `kExtensionFactories` list that calls the package's top-level
// `createExtension()` function. When no integrations are present the
// generated file falls back to an empty list so that the host runs
// without errors.
//
// Discovery and validation live in `_extension_discovery.dart`; this
// script only formats the generated Dart output.
//
// Usage:
//   dart run scripts/gen_extension_registry.dart
//
// Run via the `make ext-gen` target (which also regenerates
// `pubspec_overrides.yaml`).

import 'dart:io';

import '_extension_discovery.dart';

const String _outputFile = 'lib/extension/generated/registry.g.dart';

Future<void> main(List<String> args) async {
  final IntegrationDiscoveryResult result = discoverIntegrations();
  for (final String warning in result.warnings) {
    stderr.writeln('[gen_extension_registry] $warning');
  }

  final String body = renderRegistry(result.integrations);
  File(_outputFile).writeAsStringSync(body);

  stdout.writeln(
    '[gen_extension_registry] wrote $_outputFile '
    '(${result.integrations.length} integration(s)'
    '${result.integrations.isEmpty ? '' : ': ${result.integrations.map((DiscoveredIntegration i) => i.name).join(', ')}'}).',
  );
}

/// Render the generated `registry.g.dart` body for [integrations].
///
/// Exposed as a top-level function so the test suite can verify the
/// formatter without writing to disk.
String renderRegistry(List<DiscoveredIntegration> integrations) {
  final StringBuffer buf = StringBuffer()
    ..writeln('// AUTO-GENERATED by `make ext-gen`. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// This file is regenerated from the contents of the top-level')
    ..writeln(
      '// `integrations/` directory. When no integrations are present the',
    )
    ..writeln('// generated factory list is empty and the host runs with zero')
    ..writeln('// optional integrations registered.')
    ..writeln()
    ..writeln("import '../comerune_extension.dart';");
  for (final DiscoveredIntegration integration in integrations) {
    buf.writeln(
      "import 'package:${integration.name}/${integration.name}.dart' "
      "as ${integration.name};",
    );
  }
  buf
    ..writeln()
    ..writeln(
      '/// Factories for every integration discovered by the generator.',
    )
    ..writeln('///')
    ..writeln(
      "/// Iterated by `ExtensionLoader.loadAll()` in registration order.",
    );
  if (integrations.isEmpty) {
    buf.writeln(
      'const List<ComeruneExtension Function()> kExtensionFactories =',
    );
    buf.writeln('    <ComeruneExtension Function()>[];');
    return buf.toString();
  }
  buf.writeln('final List<ComeruneExtension Function()> kExtensionFactories =');
  buf.writeln('    <ComeruneExtension Function()>[');
  for (final DiscoveredIntegration integration in integrations) {
    buf.writeln('      ${integration.name}.createExtension,');
  }
  buf.writeln('    ];');
  return buf.toString();
}
