// Generates `pubspec_overrides.yaml` from the contents of the
// top-level `integrations/` directory.
//
// For each `integrations/<name>/pubspec.yaml` discovered, an entry
//
//   <name>:
//     path: integrations/<name>
//
// is added under `dependency_overrides:`. When the directory contains
// no integrations, the existing `pubspec_overrides.yaml` (if any) is
// removed so that `flutter pub get` resolves the host's regular
// dependencies cleanly.
//
// The generator NEVER imports or evaluates integration source code; it
// only reads `pubspec.yaml` line-by-line to extract the package name.
//
// Usage:
//   dart run scripts/gen_extension_overrides.dart
//
// Run via the `make ext-gen` target (which also regenerates
// `lib/extension/generated/registry.g.dart`).

import 'dart:io';

const String _integrationsDir = 'integrations';
const String _outputFile = 'pubspec_overrides.yaml';
const String _generatedHeader =
    '# AUTO-GENERATED by `make ext-gen`. Do not edit by hand.\n'
    '# Regenerated from the contents of the `integrations/` directory.\n'
    '# When no integrations are present this file is removed entirely.\n';

Future<void> main(List<String> args) async {
  final Directory dir = Directory(_integrationsDir);
  if (!dir.existsSync()) {
    _removeIfPresent(_outputFile);
    stdout.writeln(
      '[gen_extension_overrides] no `$_integrationsDir/` directory; '
      'removed any existing $_outputFile.',
    );
    return;
  }

  final List<_Integration> integrations = _discoverIntegrations(dir);
  if (integrations.isEmpty) {
    _removeIfPresent(_outputFile);
    stdout.writeln(
      '[gen_extension_overrides] no integrations discovered; '
      'removed any existing $_outputFile.',
    );
    return;
  }

  final StringBuffer buf = StringBuffer()
    ..write(_generatedHeader)
    ..writeln('dependency_overrides:');
  for (final _Integration integration in integrations) {
    buf
      ..writeln('  ${integration.name}:')
      ..writeln('    path: ${integration.relativePath}');
  }

  File(_outputFile).writeAsStringSync(buf.toString());
  stdout.writeln(
    '[gen_extension_overrides] wrote $_outputFile with '
    '${integrations.length} integration(s): '
    '${integrations.map((_Integration i) => i.name).join(', ')}.',
  );
}

void _removeIfPresent(String path) {
  final File file = File(path);
  if (file.existsSync()) {
    file.deleteSync();
  }
}

List<_Integration> _discoverIntegrations(Directory root) {
  final List<_Integration> found = <_Integration>[];
  final List<FileSystemEntity> children = root.listSync()
    ..sort(
      (FileSystemEntity a, FileSystemEntity b) => a.path.compareTo(b.path),
    );

  for (final FileSystemEntity child in children) {
    if (child is! Directory) {
      continue;
    }
    final File pubspec = File('${child.path}/pubspec.yaml');
    if (!pubspec.existsSync()) {
      continue;
    }
    final String? name = _readPackageName(pubspec);
    if (name == null) {
      stderr.writeln(
        '[gen_extension_overrides] skipping ${child.path}: '
        'pubspec.yaml has no `name:` field.',
      );
      continue;
    }
    if (!_isValidPackageName(name)) {
      stderr.writeln(
        '[gen_extension_overrides] skipping ${child.path}: '
        'package name "$name" is not a valid Dart identifier.',
      );
      continue;
    }
    found.add(
      _Integration(
        name: name,
        relativePath:
            '$_integrationsDir/${child.uri.pathSegments.where((String s) => s.isNotEmpty).last}',
      ),
    );
  }
  return found;
}

String? _readPackageName(File pubspec) {
  final List<String> lines = pubspec.readAsLinesSync();
  for (final String line in lines) {
    final String trimmed = line.trimLeft();
    if (!trimmed.startsWith('name:')) {
      continue;
    }
    String value = trimmed.substring('name:'.length).trim();
    final int hashIndex = value.indexOf('#');
    if (hashIndex >= 0) {
      value = value.substring(0, hashIndex).trim();
    }
    if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
      value = value.substring(1, value.length - 1);
    } else if (value.startsWith("'") &&
        value.endsWith("'") &&
        value.length >= 2) {
      value = value.substring(1, value.length - 1);
    }
    if (value.isEmpty) {
      return null;
    }
    return value;
  }
  return null;
}

bool _isValidPackageName(String name) {
  // Pub package names: lowercase letters, digits, underscores; cannot
  // start with a digit. Mirrors pub's own validator (dropping the
  // reserved-word check, which the generator does not need to reproduce
  // — pub will reject reserved names downstream anyway).
  final RegExp pattern = RegExp(r'^[a-z_][a-z0-9_]*$');
  return pattern.hasMatch(name);
}

class _Integration {
  _Integration({required this.name, required this.relativePath});
  final String name;
  final String relativePath;
}
