// Generates `lib/extension/generated/registry.g.dart` from the
// contents of the top-level `integrations/` directory.
//
// For each `integrations/<name>/pubspec.yaml` discovered, an `import`
// of `package:<name>/<name>.dart` is emitted, along with an entry in
// the `kExtensionFactories` list that calls the package's top-level
// `createExtension()` function. When no integrations are present the
// generated file falls back to an empty list so that the host runs
// without errors.
//
// The generator NEVER imports or evaluates integration source code; it
// only reads `pubspec.yaml` line-by-line to extract the package name.
//
// Usage:
//   dart run scripts/gen_extension_registry.dart
//
// Run via the `make ext-gen` target (which also regenerates
// `pubspec_overrides.yaml`).

import 'dart:io';

const String _integrationsDir = 'integrations';
const String _outputFile = 'lib/extension/generated/registry.g.dart';

Future<void> main(List<String> args) async {
  final List<_Integration> integrations = _discoverIntegrations(
    Directory(_integrationsDir),
  );

  final String body = _renderBody(integrations);
  File(_outputFile).writeAsStringSync(body);

  stdout.writeln(
    '[gen_extension_registry] wrote $_outputFile '
    '(${integrations.length} integration(s)'
    '${integrations.isEmpty ? '' : ': ${integrations.map((_Integration i) => i.name).join(', ')}'}).',
  );
}

String _renderBody(List<_Integration> integrations) {
  final StringBuffer buf = StringBuffer()
    ..writeln('// AUTO-GENERATED by `make ext-gen`. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// This file is regenerated from the contents of the top-level')
    ..writeln(
      '// `integrations/` directory. When no integrations are present the',
    )
    ..writeln('// generated factory list is empty and the host runs with zero')
    ..writeln('// optional integrations registered.')
    ..writeln()
    ..writeln("import '../comerune_extension.dart';");
  for (final _Integration integration in integrations) {
    buf.writeln(
      "import 'package:${integration.name}/${integration.name}.dart' "
      "as ${integration.aliasIdentifier};",
    );
  }
  buf
    ..writeln()
    ..writeln(
      '/// Factories for every integration discovered by the generator.',
    )
    ..writeln('///')
    ..writeln(
      "/// Iterated by `ExtensionLoader.loadAll()` in registration order.",
    );
  if (integrations.isEmpty) {
    buf.writeln(
      'const List<ComeruneExtension Function()> kExtensionFactories =',
    );
    buf.writeln('    <ComeruneExtension Function()>[];');
    return buf.toString();
  }
  buf.writeln('final List<ComeruneExtension Function()> kExtensionFactories =');
  buf.writeln('    <ComeruneExtension Function()>[');
  for (final _Integration integration in integrations) {
    buf.writeln('      ${integration.aliasIdentifier}.createExtension,');
  }
  buf.writeln('    ];');
  return buf.toString();
}

List<_Integration> _discoverIntegrations(Directory root) {
  if (!root.existsSync()) {
    return const <_Integration>[];
  }
  final List<_Integration> found = <_Integration>[];
  final List<FileSystemEntity> children = root.listSync()
    ..sort(
      (FileSystemEntity a, FileSystemEntity b) => a.path.compareTo(b.path),
    );
  for (final FileSystemEntity child in children) {
    if (child is! Directory) {
      continue;
    }
    final File pubspec = File('${child.path}/pubspec.yaml');
    if (!pubspec.existsSync()) {
      continue;
    }
    final String? name = _readPackageName(pubspec);
    if (name == null) {
      stderr.writeln(
        '[gen_extension_registry] skipping ${child.path}: '
        'pubspec.yaml has no `name:` field.',
      );
      continue;
    }
    if (!_isValidPackageName(name)) {
      stderr.writeln(
        '[gen_extension_registry] skipping ${child.path}: '
        'package name "$name" is not a valid Dart identifier.',
      );
      continue;
    }
    found.add(_Integration(name: name));
  }
  return found;
}

String? _readPackageName(File pubspec) {
  final List<String> lines = pubspec.readAsLinesSync();
  for (final String line in lines) {
    final String trimmed = line.trimLeft();
    if (!trimmed.startsWith('name:')) {
      continue;
    }
    String value = trimmed.substring('name:'.length).trim();
    final int hashIndex = value.indexOf('#');
    if (hashIndex >= 0) {
      value = value.substring(0, hashIndex).trim();
    }
    if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
      value = value.substring(1, value.length - 1);
    } else if (value.startsWith("'") &&
        value.endsWith("'") &&
        value.length >= 2) {
      value = value.substring(1, value.length - 1);
    }
    if (value.isEmpty) {
      return null;
    }
    return value;
  }
  return null;
}

bool _isValidPackageName(String name) {
  final RegExp pattern = RegExp(r'^[a-z_][a-z0-9_]*$');
  return pattern.hasMatch(name);
}

class _Integration {
  _Integration({required this.name});
  final String name;

  /// Import alias used in the generated file. Always equal to the
  /// package name; included as a separate getter so the generator can
  /// be tweaked later without touching every call site.
  String get aliasIdentifier => name;
}
