name: Flutter CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Flutter
        uses: subosito/flutter-action@e9d41e1f8c2dc12b68f14f839c4dece03e57c00d # v2.19.0
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format . --output=none --set-exit-if-changed

      - name: Run static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test
